class Exception0 {
    def func() {
        try {

        } catch (e:Exception) {

        }
    }
}
