class Exception1 {
    def func() {
        try {

        } catch (e:Exception) {
            Console.OUT.println(e);
        }
    }
}
